// This code conforms with the UFC specification version 2018.1.0
// and was automatically generated by FFC version 2019.1.0.
//
// This code was generated with the following parameters:
//

//  add_tabulate_tensor_timing:     False
//  convert_exceptions_to_warnings: False
//  cpp_optimize:                   True
//  cpp_optimize_flags:             '-O2'
//  epsilon:                        1e-14
//  error_control:                  False
//  external_include_dirs:          ['/home/felipefr/anaconda3/envs/tf/include', '/hom
//                                  e/felipefr/anaconda3/envs/tf/include/eigen3', '/ho
//                                  me/felipefr/anaconda3/envs/tf/include']
//  external_includes:              ''
//  external_libraries:             ''
//  external_library_dirs:          ''
//  form_postfix:                   False
//  format:                         'ufc'
//  generate_dummy_tabulate_tensor: False
//  max_signature_length:           0
//  no-evaluate_basis_derivatives:  True
//  optimize:                       True
//  precision:                      None
//  quadrature_degree:              None
//  quadrature_rule:                None
//  representation:                 'auto'
//  split:                          False

#include "ffc_form_0db6156370ef5c761513b8fefa998986c270ec05.h"

// Based on https://gcc.gnu.org/wiki/Visibility
#if defined _WIN32 || defined __CYGWIN__
    #ifdef __GNUC__
        #define DLL_EXPORT __attribute__ ((dllexport))
    #else
        #define DLL_EXPORT __declspec(dllexport)
    #endif
#else
    #define DLL_EXPORT __attribute__ ((visibility ("default")))
#endif

ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_cell_integral_main_otherwise::ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_cell_integral_main_otherwise() : ufc::cell_integral()
{

}

ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_cell_integral_main_otherwise::~ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_cell_integral_main_otherwise()
{

}

const std::vector<bool> & ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_cell_integral_main_otherwise::enabled_coefficients() const
{
static const std::vector<bool> enabled({true});
return enabled;
}

void ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_cell_integral_main_otherwise::tabulate_tensor(double * A,
                                    const double * const * w,
                                    const double * coordinate_dofs,
                                    int cell_orientation) const
{
    // This function was generated using 'uflacs' representation
    // with the following integrals metadata:
    // 
    // num_cells:         None
    // optimize:          True
    // precision:         16
    // quadrature_degree: 0
    // quadrature_rule:   'default'
    // representation:    'uflacs'
    // 
    // and the following integral 0 metadata:
    // 
    // estimated_polynomial_degree: 0
    // optimize:                    True
    // precision:                   16
    // quadrature_degree:           0
    // quadrature_rule:             'default'
    // representation:              'uflacs'
    // Precomputed values of basis functions and precomputations
    // FE* dimensions: [entities][points][dofs]
    // PI* dimensions: [entities][dofs][dofs] or [entities][dofs]
    // PM* dimensions: [entities][dofs][dofs]
    alignas(32) static const double FE15_C0_D01_Q1[1][1][2] = { { { -1.0, 1.0 } } };
    // Unstructured piecewise computations
    const double w0_d1_c1 = w[0][3] * FE15_C0_D01_Q1[0][0][0] + w[0][5] * FE15_C0_D01_Q1[0][0][1];
    const double J_c0 = coordinate_dofs[0] * FE15_C0_D01_Q1[0][0][0] + coordinate_dofs[2] * FE15_C0_D01_Q1[0][0][1];
    const double J_c3 = coordinate_dofs[1] * FE15_C0_D01_Q1[0][0][0] + coordinate_dofs[5] * FE15_C0_D01_Q1[0][0][1];
    const double J_c1 = coordinate_dofs[0] * FE15_C0_D01_Q1[0][0][0] + coordinate_dofs[4] * FE15_C0_D01_Q1[0][0][1];
    const double J_c2 = coordinate_dofs[1] * FE15_C0_D01_Q1[0][0][0] + coordinate_dofs[3] * FE15_C0_D01_Q1[0][0][1];
    double w0_d0_c1 = 0.0;
    for (int ic = 0; ic < 2; ++ic)
        w0_d0_c1 += w[0][ic + 3] * FE15_C0_D01_Q1[0][0][ic];
    double w0_d0_c0 = 0.0;
    for (int ic = 0; ic < 2; ++ic)
        w0_d0_c0 += w[0][ic] * FE15_C0_D01_Q1[0][0][ic];
    const double w0_d1_c0 = w[0][0] * FE15_C0_D01_Q1[0][0][0] + w[0][2] * FE15_C0_D01_Q1[0][0][1];
    const double J_c0 = coordinate_dofs[0] * FE15_C0_D01_Q1[0][0][0] + coordinate_dofs[2] * FE15_C0_D01_Q1[0][0][1];
    const double J_c3 = coordinate_dofs[1] * FE15_C0_D01_Q1[0][0][0] + coordinate_dofs[5] * FE15_C0_D01_Q1[0][0][1];
    const double J_c1 = coordinate_dofs[0] * FE15_C0_D01_Q1[0][0][0] + coordinate_dofs[4] * FE15_C0_D01_Q1[0][0][1];
    const double J_c2 = coordinate_dofs[1] * FE15_C0_D01_Q1[0][0][0] + coordinate_dofs[3] * FE15_C0_D01_Q1[0][0][1];
    alignas(32) double sp[57];
    sp[0] = J_c0 * J_c3;
    sp[1] = J_c1 * J_c2;
    sp[2] = sp[0] + -1 * sp[1];
    sp[3] = J_c0 / sp[2];
    sp[4] = w0_d1_c1 * sp[3];
    sp[5] = -1 * J_c1 / sp[2];
    sp[6] = w0_d0_c1 * sp[5];
    sp[7] = sp[4] + sp[6];
    sp[8] = J_c3 / sp[2];
    sp[9] = w0_d0_c0 * sp[8];
    sp[10] = -1 * J_c2 / sp[2];
    sp[11] = w0_d1_c0 * sp[10];
    sp[12] = sp[9] + sp[11];
    sp[13] = sp[7] + sp[12];
    sp[14] = sp[7] + sp[7];
    sp[15] = sp[13] + 0.5 * sp[14];
    sp[16] = J_c0 * J_c3;
    sp[17] = J_c1 * J_c2;
    sp[18] = sp[16] + -1 * sp[17];
    sp[19] = J_c0 / sp[18];
    sp[20] = -1 * J_c1 / sp[18];
    sp[21] = sp[19] + sp[19];
    sp[22] = sp[20] + sp[20];
    sp[23] = sp[15] * (0.5 * sp[21]);
    sp[24] = sp[15] * (0.5 * sp[22]);
    sp[25] = w0_d1_c0 * sp[3];
    sp[26] = w0_d0_c0 * sp[5];
    sp[27] = sp[25] + sp[26];
    sp[28] = w0_d0_c1 * sp[8];
    sp[29] = w0_d1_c1 * sp[10];
    sp[30] = sp[28] + sp[29];
    sp[31] = sp[27] + sp[30];
    sp[32] = J_c3 / sp[18];
    sp[33] = -1 * J_c2 / sp[18];
    sp[34] = 0.5 * sp[31] * (0.5 * sp[33]);
    sp[35] = 0.5 * sp[31] * (0.5 * sp[32]);
    sp[36] = 0.5 * sp[31] * (0.5 * sp[19]);
    sp[37] = 0.5 * sp[31] * (0.5 * sp[20]);
    sp[38] = sp[23] + sp[34];
    sp[39] = sp[24] + sp[35];
    sp[40] = sp[12] + sp[12];
    sp[41] = sp[13] + 0.5 * sp[40];
    sp[42] = sp[33] + sp[33];
    sp[43] = sp[32] + sp[32];
    sp[44] = sp[41] * (0.5 * sp[42]);
    sp[45] = sp[41] * (0.5 * sp[43]);
    sp[46] = sp[44] + sp[36];
    sp[47] = sp[45] + sp[37];
    sp[48] = sp[38] + sp[34];
    sp[49] = sp[39] + sp[35];
    sp[50] = sp[46] + sp[36];
    sp[51] = sp[47] + sp[37];
    sp[52] = std::abs(sp[18]);
    sp[53] = -1 * sp[48] * sp[52];
    sp[54] = -1 * sp[49] * sp[52];
    sp[55] = -1 * sp[50] * sp[52];
    sp[56] = -1 * sp[51] * sp[52];
    A[0] = -0.5 * sp[56] + -0.5 * sp[55];
    A[1] = 0.5 * sp[56];
    A[2] = 0.5 * sp[55];
    A[3] = -0.5 * sp[54] + -0.5 * sp[53];
    A[4] = 0.5 * sp[54];
    A[5] = 0.5 * sp[53];
}

extern "C" DLL_EXPORT ufc::cell_integral * create_ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_cell_integral_main_otherwise()
{
  return new ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_cell_integral_main_otherwise();
}


ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main() : ufc::form()
{
    // Do nothing
}

ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::~ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main()
{
    // Do nothing
}

const char * ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::signature() const
{
    return "dc83a73a9babbaae4d60ca8407ad9851a5d4c37a36aba8ddd6c46684e66a59c71c3d36868a12f6ba88cb17d4a9fd1567ac66003810e82b504f05e7207cbe4ec6";
}

std::size_t ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::rank() const
{
    return 1;
}

std::size_t ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::num_coefficients() const
{
    return 1;
}

std::size_t ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::original_coefficient_position(std::size_t i) const
{
    if (i >= 1)
    {
        throw std::runtime_error("Invalid original coefficient index.");
    }
    static const std::vector<std::size_t> position = {0};
    return position[i];
}

ufc::finite_element * ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::create_coordinate_finite_element() const
{
    return create_ffc_element_5a6e58c52ad740db73f7969d0f458213c2cc2f9a_finite_element_main();
}

ufc::dofmap * ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::create_coordinate_dofmap() const
{
    return create_ffc_element_5a6e58c52ad740db73f7969d0f458213c2cc2f9a_dofmap_main();
}

ufc::coordinate_mapping * ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::create_coordinate_mapping() const
{
    return create_ffc_coordinate_mapping_e6b48bfd93cd59103fbcb0b524e220bd4de595a5_coordinate_mapping_main();
}

ufc::finite_element * ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::create_finite_element(std::size_t i) const
{
    switch (i)
    {
    case 0:
        return create_ffc_element_5a6e58c52ad740db73f7969d0f458213c2cc2f9a_finite_element_main();
    case 1:
        return create_ffc_element_5a6e58c52ad740db73f7969d0f458213c2cc2f9a_finite_element_main();
    default:
        return nullptr;
    }
}

ufc::dofmap * ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::create_dofmap(std::size_t i) const
{
    switch (i)
    {
    case 0:
        return create_ffc_element_5a6e58c52ad740db73f7969d0f458213c2cc2f9a_dofmap_main();
    case 1:
        return create_ffc_element_5a6e58c52ad740db73f7969d0f458213c2cc2f9a_dofmap_main();
    default:
        return nullptr;
    }
}

std::size_t ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::max_cell_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::max_exterior_facet_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::max_interior_facet_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::max_vertex_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::max_custom_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::max_cutcell_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::max_interface_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::max_overlap_subdomain_id() const
{
    return 0;
}

bool ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::has_cell_integrals() const
{
    return true;
}

bool ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::has_exterior_facet_integrals() const
{
    return false;
}

bool ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::has_interior_facet_integrals() const
{
    return false;
}

bool ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::has_vertex_integrals() const
{
    return false;
}

bool ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::has_custom_integrals() const
{
    return false;
}

bool ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::has_cutcell_integrals() const
{
    return false;
}

bool ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::has_interface_integrals() const
{
    return false;
}

bool ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::has_overlap_integrals() const
{
    return false;
}

ufc::cell_integral * ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::create_cell_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::exterior_facet_integral * ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::create_exterior_facet_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::interior_facet_integral * ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::create_interior_facet_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::vertex_integral * ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::create_vertex_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::custom_integral * ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::create_custom_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::cutcell_integral * ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::create_cutcell_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::interface_integral * ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::create_interface_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::overlap_integral * ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::create_overlap_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::cell_integral * ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::create_default_cell_integral() const
{
    return create_ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_cell_integral_main_otherwise();
}

ufc::exterior_facet_integral * ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::create_default_exterior_facet_integral() const
{
    return nullptr;
}

ufc::interior_facet_integral * ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::create_default_interior_facet_integral() const
{
    return nullptr;
}

ufc::vertex_integral * ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::create_default_vertex_integral() const
{
    return nullptr;
}

ufc::custom_integral * ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::create_default_custom_integral() const
{
    return nullptr;
}

ufc::cutcell_integral * ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::create_default_cutcell_integral() const
{
    return nullptr;
}

ufc::interface_integral * ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::create_default_interface_integral() const
{
    return nullptr;
}

ufc::overlap_integral * ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main::create_default_overlap_integral() const
{
    return nullptr;
}

extern "C" DLL_EXPORT ufc::form * create_ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main()
{
  return new ffc_form_0db6156370ef5c761513b8fefa998986c270ec05_form_main();
}

